PENDING_INVITATION_STATUS='pending'
TAKEN_INVITATION_STATUS='taken'

ACCEPTED_MESA_INVITATION= 'accepted'
PENDING_MESA_INVITATION= 'pending'
EXPIRED_MESA_INVITATION= 'expired'
REJECTED_MESA_INVITATION= 'rejected'

ROLE_ADMIN = 1
