PENDING_INVITATION_STATUS='pending'
TAKEN_INVITATION_STATUS='taken'

ACCEPTED_MESA_INVITATION= 'accepted'
PENDING_MESA_INVITATION= 'pending'
EXPIRED_MESA_INVITATION= 'expired'
REJECTED_MESA_INVITATION= 'rejected'
WAITING_MESA_INVITATION= 'waiting' #next user in chair list will be in waiting stateunless his earlier user 18 hrs are expired

MESA_IS_CREATED= 'created'
MESA_IS_AUTHORIZED= 'authorized'
MESA_IS_STARTED= 'started'
MESA_IS_COMPLETED= 'completed'

ROLE_MASTER = 1
ROLE_ADMIN = 2
ROLE_LEADER = 3
ROLE_CURATOR = 4
ROLE_UNCONCIOUS = 5
ROLE_COMMONFLAGGER = 6
ROLE_HARDINPUT = 7
ROLE_FAVORITED = 8
ROLE_COMMON = 9

VALID_ADMIN_USERS = [ROLE_MASTER,ROLE_ADMIN,ROLE_LEADER]
