PENDING_INVITATION_STATUS='pending'
TAKEN_INVITATION_STATUS='taken'

ACCEPTED_MESA_INVITATION= 'accepted'
PENDING_MESA_INVITATION= 'pending'
EXPIRED_MESA_INVITATION= 'expired'
REJECTED_MESA_INVITATION= 'rejected'

MESA_IS_CREATED= 'created'
MESA_IS_AUTHORIZED= 'authorized'
MESA_IS_STARTED= 'started'
MESA_IS_COMPLETED= 'completed'

ROLE_ADMIN = 1
ROLE_LEADER = 2
ROLE_CURATOR = 3
ROLE_COMMONFLAGGER = 4
ROLE_HARDINPUT = 5
ROLE_FAVORITED = 6
ROLE_COMMON = 7
ROLE_MASTER = 8
